# Generated by Django 2.2.10 on 2020-04-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-id',), 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',), 'verbose_name': 'Обзор', 'verbose_name_plural': 'Обзоры'},
        ),
    ]
