# Generated by Django 2.2.10 on 2020-04-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='attempt_value',
        ),
    ]
