# Generated by Django 2.2.10 on 2020-04-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_player_attempt_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_value',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
